import os
import subprocess
from datetime import datetime
from jinja2 import Template

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

REPORT_TEMPLATE = """# SPECTRE — Penetration Test Report

**Engagement:** {{ engagement.name }}
**Target:** {{ engagement.target }}
**Type:** {{ engagement.type }}
**Date:** {{ date }}
**Status:** {{ engagement.status }}

---

## Executive Summary

This report documents the findings from a penetration test conducted against **{{ engagement.target }}**.
A total of **{{ findings | length }}** findings were identified across **{{ severity_counts }}**.

---

## Findings

{% for f in findings %}
### [{{ f.severity | upper }}] {{ f.title }}

| Field       | Value |
|-------------|-------|
| Host        | {{ f.host or 'N/A' }} |
| Port        | {{ f.port or 'N/A' }} |
| Tool        | {{ f.tool or 'N/A' }} |
| MITRE TTP   | {{ f.ttp or 'N/A' }} |
| Severity    | {{ f.severity | upper }} |
| Status      | {{ f.status }} |

**Description:**
{{ f.description or 'No description provided.' }}

**Evidence:**
```
{{ f.evidence or 'No evidence captured.' }}
```

---
{% endfor %}

## Tool Run Timeline

| Time | Tool | Success |
|------|------|---------|
{% for r in tool_runs %}| {{ r.timestamp[:19] }} | {{ r.tool_name }} | {{ '✅' if r.success else '❌' }} |
{% endfor %}

---

*Generated by SPECTRE — {{ date }}*
"""


class ReportGenerator:
    def __init__(self, store):
        self.store = store

    def generate(self, engagement_id: int, output_format: str = "md") -> str:
        engagement = self.store.get_engagement(engagement_id)
        if not engagement:
            raise ValueError(f"Engagement {engagement_id} not found")

        findings = self.store.list_findings(engagement_id)
        tool_runs = self.store.list_tool_runs(engagement_id)

        # Sort findings by severity
        findings.sort(key=lambda f: SEVERITY_ORDER.get(f.get("severity", "info"), 99))

        # Severity counts summary
        counts = {}
        for f in findings:
            sev = f.get("severity", "info")
            counts[sev] = counts.get(sev, 0) + 1
        severity_counts = ", ".join([f"{v} {k}" for k, v in counts.items()])

        # Render template
        template = Template(REPORT_TEMPLATE)
        rendered = template.render(
            engagement=engagement,
            findings=findings,
            tool_runs=tool_runs,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            severity_counts=severity_counts or "0 findings"
        )

        # Save output
        output_dir = os.path.expanduser(f"~/.spectre/reports")
        os.makedirs(output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_path = os.path.join(output_dir, f"report_{engagement_id}_{timestamp}")

        md_path = f"{base_path}.md"
        with open(md_path, "w") as f:
            f.write(rendered)

        if output_format == "pdf":
            pdf_path = f"{base_path}.pdf"
            try:
                subprocess.run(
                    ["pandoc", md_path, "-o", pdf_path, "--pdf-engine=xelatex"],
                    check=True, capture_output=True
                )
                return pdf_path
            except Exception:
                # fallback to md if pandoc not available
                return md_path

        return md_path
