import os
from typing import Optional

# sliver-py is the official Sliver gRPC client
# Install: pip install sliver-py
try:
    from sliver import SliverClientConfig, SliverClient
    SLIVER_AVAILABLE = True
except ImportError:
    SLIVER_AVAILABLE = False

DEFAULT_CONFIG = os.path.expanduser("~/.sliver-client/configs/default.cfg")


class SliverIntegration:
    """
    Read-only Sliver C2 integration for SPECTRE.

    Connects to a running Sliver server via gRPC and reads:
    - Active sessions (beacons)
    - Session details (hostname, user, OS, arch, privileges)

    The agent uses this to:
    - Know when a shell is available on a target
    - Suggest post-exploitation steps based on session context
    - Check privilege level (SYSTEM / admin / user)

    SPECTRE never executes commands via Sliver autonomously.
    All C2 actions require operator confirmation.
    """

    def __init__(self, config_path: str = DEFAULT_CONFIG):
        self.config_path = config_path
        self.client      = None
        self.connected   = False

    def is_available(self) -> bool:
        """Check if sliver-py is installed."""
        return SLIVER_AVAILABLE

    async def connect(self) -> bool:
        """
        Connect to Sliver server using config file.
        Config file is generated by: sliver-client export-config
        """
        if not SLIVER_AVAILABLE:
            return False

        if not os.path.exists(self.config_path):
            return False

        try:
            config       = SliverClientConfig.parse_config_file(self.config_path)
            self.client  = SliverClient(config)
            await self.client.connect()
            self.connected = True
            return True
        except Exception:
            self.connected = False
            return False

    async def get_sessions(self) -> list:
        """
        Return all active Sliver sessions.

        Each session dict contains:
        - id, name, hostname, username, os, arch
        - uid, gid, pid
        - is_privileged (True if SYSTEM or root)
        - remote_address
        - last_checkin
        """
        if not self.connected or not self.client:
            return []

        try:
            sessions = await self.client.sessions()
            result   = []

            for s in sessions:
                result.append({
                    "id":             s.ID,
                    "name":           s.Name,
                    "hostname":       s.Hostname,
                    "username":       s.Username,
                    "uid":            s.UID,
                    "gid":            s.GID,
                    "os":             s.OS,
                    "arch":           s.Arch,
                    "pid":            s.PID,
                    "remote_address": s.RemoteAddress,
                    "is_privileged":  self._is_privileged(s),
                    "last_checkin":   str(s.LastCheckin),
                })

            return result

        except Exception:
            return []

    async def get_beacons(self) -> list:
        """Return all active Sliver beacons (async implants)."""
        if not self.connected or not self.client:
            return []

        try:
            beacons = await self.client.beacons()
            result  = []

            for b in beacons:
                result.append({
                    "id":             b.ID,
                    "name":           b.Name,
                    "hostname":       b.Hostname,
                    "username":       b.Username,
                    "os":             b.OS,
                    "arch":           b.Arch,
                    "remote_address": b.RemoteAddress,
                    "is_privileged":  self._is_privileged(b),
                    "interval":       b.Interval,
                    "jitter":         b.Jitter,
                    "next_checkin":   str(b.NextCheckin),
                })

            return result

        except Exception:
            return []

    def _is_privileged(self, session) -> bool:
        """Detect if session is running as SYSTEM or root."""
        try:
            uid      = str(session.UID).strip()
            username = str(session.Username).strip().lower()
            os_name  = str(session.OS).strip().lower()

            if "windows" in os_name:
                return "system" in username or "administrator" in username
            else:
                return uid == "0"
        except Exception:
            return False

    def suggest_postex(self, session: dict) -> list:
        """
        Given a session, suggest relevant post-exploitation steps.
        Returns list of suggestion strings with TTPs.

        This is the key value of C2 integration in SPECTRE —
        the agent can see session context and suggest smart next steps.
        """
        suggestions = []
        os_name     = session.get("os", "").lower()
        privileged  = session.get("is_privileged", False)
        username    = session.get("username", "").lower()

        if "windows" in os_name:
            if not privileged:
                suggestions += [
                    "[T1068] Local privilege escalation — run winpeas, check unquoted service paths",
                    "[T1134] Token impersonation — try Incognito / PrintSpoofer",
                    "[T1055] Process injection — migrate to higher-priv process",
                ]
            else:
                suggestions += [
                    "[T1003.001] Dump LSASS — use mimikatz or impacket secretsdump",
                    "[T1021.002] Lateral movement via SMB — pass the hash with crackmapexec",
                    "[T1087]     Enumerate AD — run bloodhound-python from this context",
                    "[T1558.003] Kerberoasting — request TGS for SPNs",
                    "[T1548.002] UAC bypass — if admin but not SYSTEM",
                ]

        elif "linux" in os_name:
            if not privileged:
                suggestions += [
                    "[T1068] Check SUID binaries: find / -perm -4000 2>/dev/null",
                    "[T1068] Check sudo rights: sudo -l",
                    "[T1068] Check writable cron jobs and services",
                    "[T1552] Search for credentials in config files and history",
                ]
            else:
                suggestions += [
                    "[T1003] Dump /etc/shadow for offline cracking",
                    "[T1021] SSH key harvesting from ~/.ssh/",
                    "[T1087] Enumerate internal network from pivot point",
                ]

        return suggestions

    async def disconnect(self):
        if self.client and self.connected:
            try:
                await self.client.close()
            except Exception:
                pass
            self.connected = False
